# Generated by Django 5.0.8 on 2024-09-03 11:35

import machina.models.fields
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models

import lacommunaute.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Nom")),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=400, null=True, verbose_name="Description courte (SEO)"),
                ),
                (
                    "description",
                    machina.models.fields.MarkupTextField(
                        blank=True, no_rendered_field=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        help_text="1200x600 recommandé",
                        storage=storages.backends.s3.S3Storage(
                            bucket_name=settings.AWS_STORAGE_BUCKET_NAME, file_overwrite=False
                        ),
                        upload_to="logos/",
                        validators=[lacommunaute.utils.validators.validate_image_size],
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="Lien vers le site du partenaire")),
                ("_description_rendered", models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "ordering": ["-created"],
            },
        ),
    ]
