# Generated by Django 5.0.9 on 2024-09-30 13:52

import storages.backends.s3
from django.db import migrations, models

import lacommunaute.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0002_alter_partner_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="logo",
        ),
        migrations.AddField(
            model_name="partner",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(bucket_name="private-bucket", file_overwrite=False),
                upload_to="",
                validators=[lacommunaute.utils.validators.validate_image_size],
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="short_description",
            field=models.CharField(default="to be updated", max_length=400, verbose_name="Short Description"),
            preserve_default=False,
        ),
    ]
