# Generated by Django 4.1.2 on 2022-10-18 09:05

import machina.apps.forum.abstract_models
import machina.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                (
                    "description",
                    machina.models.fields.MarkupTextField(
                        blank=True,
                        no_rendered_field=True,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "image",
                    machina.models.fields.ExtendedImageField(
                        blank=True,
                        null=True,
                        upload_to=machina.apps.forum.abstract_models.get_forum_image_upload_to,
                        verbose_name="Forum image",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="Forum link"),
                ),
                (
                    "link_redirects",
                    models.BooleanField(
                        default=False,
                        help_text="Records the number of times a forum link was clicked",
                        verbose_name="Track link redirects count",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Default forum"),
                            (1, "Category forum"),
                            (2, "Link forum"),
                        ],
                        db_index=True,
                        verbose_name="Forum type",
                    ),
                ),
                (
                    "direct_posts_count",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        editable=False,
                        verbose_name="Direct number of posts",
                    ),
                ),
                (
                    "direct_topics_count",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        editable=False,
                        verbose_name="Direct number of topics",
                    ),
                ),
                (
                    "link_redirects_count",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        editable=False,
                        verbose_name="Track link redirects count",
                    ),
                ),
                (
                    "last_post_on",
                    models.DateTimeField(blank=True, null=True, verbose_name="Last post added on"),
                ),
                (
                    "display_sub_forum_list",
                    models.BooleanField(
                        default=True,
                        help_text="Displays this forum on the legend of its parent-forum (sub forums list)",
                        verbose_name="Display in parent-forums legend",
                    ),
                ),
                (
                    "_description_rendered",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name": "Forum",
                "verbose_name_plural": "Forums",
                "ordering": ["tree_id", "lft"],
                "abstract": False,
            },
        ),
    ]
