# Generated by Django 4.1.3 on 2022-11-03 09:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("forum", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="invitation_token",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="forum",
            name="members_group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.group", verbose_name="Members Group"
            ),
        ),
    ]
