# Generated by Django 4.1.3 on 2022-11-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0004_alter_forum_invitation_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="is_highlighted",
            field=models.BooleanField(default=False, verbose_name="affichée sur la homepage"),
        ),
        migrations.AddField(
            model_name="forum",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="privée"),
        ),
    ]
