# Generated by Django 4.1.4 on 2022-12-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0005_forum_is_highlighted_forum_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="target_audience",
            field=models.IntegerField(default=0),
        ),
    ]
