# Generated by Django 4.1.5 on 2023-01-31 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0006_forum_target_audience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forum",
            name="is_highlighted",
        ),
    ]
