# Generated by Django 4.1.7 on 2023-03-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("forum", "0007_remove_forum_is_highlighted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="members_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
                verbose_name="Members Group",
            ),
        ),
    ]
