# Generated by Django 4.1.7 on 2023-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0008_alter_forum_members_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="job_offer_is_allowed",
            field=models.BooleanField(default=False, verbose_name="offres d'emploi"),
        ),
    ]
