# Generated by Django 4.2.2 on 2023-06-28 08:37

from django.db import migrations, models


def add_kind_to_forums(apps, schema_editor):
    Forum = apps.get_model("forum", "Forum")
    Forum.objects.filter(is_newsfeed=True).update(kind="NEWS")
    Forum.objects.filter(is_newsfeed=False, is_private=True).update(kind="PRIVATE_FORUM")
    Forum.objects.filter(is_newsfeed=False, is_private=False, type=1).update(kind="DOCUMENTATION")


def remove_kind_from_forums(apps, schema_editor):
    Forum = apps.get_model("forum", "Forum")
    Forum.objects.filter(kind="NEWS").update(is_newsfeed=True, is_private=False)
    Forum.objects.filter(kind="PRIVATE_FORUM").update(is_private=True, is_newsfeed=False)
    Forum.objects.filter(kind="DOCUMENTATION").update(is_private=False, is_newsfeed=False, type=1)


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0010_forum_is_newsfeed"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="kind",
            field=models.CharField(
                choices=[
                    ("PUBLIC_FORUM", "Espace public"),
                    ("PRIVATE_FORUM", "Espace privé"),
                    ("NEWS", "Actualités"),
                ],
                default="PUBLIC_FORUM",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.RunPython(add_kind_to_forums, remove_kind_from_forums),
        migrations.RemoveField(
            model_name="forum",
            name="is_newsfeed",
        ),
        migrations.RemoveField(
            model_name="forum",
            name="is_private",
        ),
    ]
