# Generated by Django 4.2.2 on 2023-06-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0011_forum_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="short_description",
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="Description courte (SEO)"),
        ),
    ]
