# Generated by Django 5.0.6 on 2024-06-13 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0014_forumrating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forumrating",
            options={
                "ordering": ("-created",),
                "verbose_name": "Notation Forum",
                "verbose_name_plural": "Notations Forum",
            },
        ),
    ]
