# Generated by Django 5.0.7 on 2024-08-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0015_alter_forumrating_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="certified",
            field=models.BooleanField(default=False, verbose_name="Certifié par la communauté de l'inclusion"),
        ),
    ]
