# Generated by Django 5.0.8 on 2024-08-29 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0017_forum_tags"),
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="partner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="partner.partner"
            ),
        ),
    ]
