# Generated by Django 5.0.8 on 2024-09-05 10:02

from django.db import migrations


def delete_private_forums(apps, schema_editor):
    Forum = apps.get_model("forum", "Forum")
    Forum.objects.filter(kind="PRIVATE_FORUM").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0018_forum_partner"),
    ]

    operations = [
        migrations.RunPython(delete_private_forums),
    ]
