# Generated by Django 5.0.8 on 2024-09-05 10:28

from django.db import migrations, models


def delete_empty_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0019_del_private_forum_20240905_1202"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forum",
            name="invitation_token",
        ),
        migrations.RemoveField(
            model_name="forum",
            name="members_group",
        ),
        migrations.AlterField(
            model_name="forum",
            name="kind",
            field=models.CharField(
                choices=[("PUBLIC_FORUM", "Espace public"), ("NEWS", "Actualités")],
                default="PUBLIC_FORUM",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.RunPython(delete_empty_groups),
    ]
