# Generated by Django 5.0.8 on 2024-09-05 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0020_remove_forum_invitation_token_and_more"),
        ("search", "0002_remove_kind_in_materialized_view"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forum",
            name="kind",
        ),
    ]
