# Generated by Django 4.1.7 on 2023-02-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, verbose_name="Nom")),
                ("date", models.DateField(verbose_name="Date")),
                ("value", models.IntegerField(verbose_name="Valeur")),
                (
                    "period",
                    models.CharField(
                        choices=[("month", "Month"), ("week", "Week"), ("day", "Day")],
                        max_length=10,
                        verbose_name="Période",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stat",
                "verbose_name_plural": "Stats",
                "ordering": ["date", "period", "name"],
                "unique_together": {("name", "date", "period")},
            },
        ),
    ]
