# Generated by Django 5.0.6 on 2024-06-17 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum_stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchCollectionPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("start_date", models.DateField(help_text="The start of the period", verbose_name="Start date")),
                ("end_date", models.DateField(help_text="The end of the period", verbose_name="End date")),
            ],
            options={
                "verbose_name": "Search Collection Period",
                "verbose_name_plural": "Search Collection Periods",
                "ordering": ["-end_date", "-start_date"],
                "unique_together": {("start_date", "end_date")},
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.TextField(help_text="The search query made by the user")),
                ("nb_visits", models.PositiveIntegerField(verbose_name="Number visits")),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to="forum_stats.searchcollectionperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Query",
                "verbose_name_plural": "Search Queries",
                "ordering": ["-period", "label"],
            },
        ),
    ]
