# Generated by Django 5.0.1 on 2024-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedDomainName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("domain", models.CharField(max_length=253, unique=True, verbose_name="domaine")),
                ("reason", models.CharField(max_length=255, verbose_name="raison")),
            ],
            options={
                "verbose_name": "nom de domaine bloqué",
                "verbose_name_plural": "nom de domaines bloqués",
            },
        ),
        migrations.CreateModel(
            name="BlockedEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                ("reason", models.CharField(max_length=255, verbose_name="raison")),
            ],
            options={
                "verbose_name": "email bloqué",
                "verbose_name_plural": "emails bloqués",
            },
        ),
    ]
