# Generated by Django 5.0.6 on 2024-06-12 11:31

from django.db import migrations

from lacommunaute.forum_moderation.enums import BlockedPostReason


def migrate_block_reason_to_choice_field(apps, schema_editor):
    BlockedPost = apps.get_model("forum_moderation", "BlockedPost")

    for post in BlockedPost.objects.all():
        if post.block_reason not in BlockedPostReason.labels:
            continue
        post.block_reason = BlockedPostReason(
            BlockedPostReason.values[BlockedPostReason.labels.index(post.block_reason)]
        )
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ("forum_moderation", "0003_blockedpost"),
    ]

    operations = [migrations.RunPython(migrate_block_reason_to_choice_field)]
