# Generated by Django 5.0.9 on 2024-11-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identity_provider",
            field=models.CharField(
                choices=[("IC", "Inclusion Connect"), ("PC", "Pro Connect")], default="IC", max_length=2
            ),
            preserve_default=False,
        ),
    ]
