# Generated by Django 5.0.9 on 2024-11-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_identity_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="identity_provider",
            field=models.CharField(
                choices=[("IC", "Inclusion Connect"), ("PC", "Pro Connect"), ("ML", "Magic Link")], max_length=2
            ),
        ),
    ]
