# Generated by Django 5.0.9 on 2024-11-26 13:03

from django.db import migrations

import lacommunaute.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_identity_provider"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", lacommunaute.users.models.UserManager()),
            ],
        ),
    ]
