# Generated by Django 5.1.5 on 2025-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_run_management"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLastSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="email"),
                ),
                (
                    "email_hash",
                    models.CharField(max_length=255, null=True, verbose_name="email hash"),
                ),
                ("last_seen_at", models.DateTimeField(verbose_name="last seen at")),
                (
                    "last_seen_kind",
                    models.CharField(
                        choices=[
                            ("POST", "message"),
                            ("DSP", "Diag Parcours IAE"),
                            ("EVENT", "évènement public"),
                            ("UPVOTE", "abonnement"),
                            ("FORUM_RATING", "notation de forum"),
                            ("LOGGED", "connexion"),
                            ("VISITED", "notification cliquée"),
                        ],
                        max_length=12,
                        verbose_name="last seen kind",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="deleted at"),
                ),
            ],
        ),
    ]
