# Generated by Django 5.1.5 on 2025-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_run_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillastseen",
            name="missyou_send_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="miss you sent at"),
        ),
    ]
