# Generated by Django 4.1.7 on 2023-03-14 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum_conversation", "0005_remove_post_upvoters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum_upvote", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertifiedPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certified_post",
                        to="forum_conversation.post",
                        verbose_name="Post",
                    ),
                ),
                (
                    "topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certified_post",
                        to="forum_conversation.topic",
                        verbose_name="Topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certified_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
