# Generated by Django 4.2.3 on 2023-07-19 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("forum_upvote", "0002_certifiedpost"), ("forum_conversation", "0007_certifiedpost")]

    operations = [
        migrations.DeleteModel(
            name="CertifiedPost",
        ),
    ]
