# Generated by Django 4.1.2 on 2022-10-18 09:05

import django.db.models.deletion
import machina.apps.forum_conversation.forum_attachments.abstract_models
from django.db import migrations, models


get_attachment_file_upload_to = (
    machina.apps.forum_conversation.forum_attachments.abstract_models.get_attachment_file_upload_to
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forum_conversation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=get_attachment_file_upload_to,
                        verbose_name="File",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Comment"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="forum_conversation.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "abstract": False,
            },
        ),
    ]
