# Generated by Django 4.1.2 on 2022-10-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum_conversation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="username",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Adresse email"),
        ),
    ]
