# Generated by Django 4.1.3 on 2022-11-07 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum_conversation", "0002_alter_post_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="likers",
            field=models.ManyToManyField(
                blank=True, related_name="topic_likes", to=settings.AUTH_USER_MODEL, verbose_name="Likers"
            ),
        ),
    ]
