# Generated by Django 4.1.3 on 2022-12-06 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum_conversation", "0003_topic_likers"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="upvoters",
            field=models.ManyToManyField(
                blank=True, related_name="post_upvotes", to=settings.AUTH_USER_MODEL, verbose_name="Upvoters"
            ),
        ),
    ]
