# Generated by Django 4.1.4 on 2022-12-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum_conversation", "0004_post_upvoters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="upvoters",
        ),
    ]
