# Generated by Django 4.1.7 on 2023-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_conversation", "0005_remove_post_upvoters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Default topic"), (1, "Sticky"), (2, "Announce"), (3, "Job offer")],
                db_index=True,
                verbose_name="Topic type",
            ),
        ),
    ]
