# Generated by Django 4.2 on 2023-04-12 07:26

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("forum_conversation", "0005_remove_post_upvoters"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
