# Generated by Django 4.2.3 on 2023-07-19 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum_conversation", "0006_topic_tags"),
        ("forum_upvote", "0002_certifiedpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertifiedPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certified_post",
                        to="forum_conversation.post",
                        verbose_name="Post",
                    ),
                ),
                (
                    "topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certified_post",
                        to="forum_conversation.topic",
                        verbose_name="Topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certified_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.RunSQL(
            """
            INSERT INTO forum_conversation_certifiedpost (
                id, created, updated, post_id, topic_id, user_id
                )
                SELECT
                id, created, updated, post_id, topic_id, user_id
                FROM
                forum_upvote_certifiedpost;
            SELECT
                setval(
                    pg_get_serial_sequence('"forum_conversation_certifiedpost"','id'),
                    coalesce(max("id"), 1),
                    max("id") IS NOT null
                    )
            FROM
                "forum_conversation_certifiedpost";
            """,
            reverse_sql="""
            INSERT INTO forum_upvote_certifiedpost (id, created, updated, post_id, topic_id, user_id)
            SELECT id, created, updated, post_id, topic_id, user_id FROM forum_conversation_certifiedpost;
            """,
        ),
    ]
