# Generated by Django 5.1.5 on 2025-02-11 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum_conversation", "0008_remove_topic_likers"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE forum_conversation_post
            SET username = LOWER(username);
            """,
            elidable=True,
        ),
        migrations.RunSQL(
            """
            UPDATE forum_conversation_post
            SET username = regexp_replace(username, '@pole-emploi.fr$', '@francetravail.fr')
            WHERE username LIKE '%@pole-emploi.fr';
            """,
            elidable=True,
        ),
    ]
