# Generated by Django 5.0.9 on 2024-09-19 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0001_initial"),
        ("forum_conversation", "0008_remove_topic_likers"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topics",
                to="documentation.document",
            ),
        ),
    ]
