# Generated by Django 5.0.9 on 2024-10-02 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentation", "0002_documentrating"),
        ("forum_conversation", "0008_remove_topic_likers"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topics",
                to="documentation.document",
            ),
        ),
    ]
