# Generated by Django 5.0.6 on 2024-06-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum_conversation", "0008_remove_topic_likers"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("username", models.EmailField(blank=True, max_length=254, null=True, verbose_name="Adresse email")),
                ("content", models.CharField(verbose_name="Content")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
