# Generated by Django 5.0.6 on 2024-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum_conversation", "0009_blockedpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockedpost",
            name="block_reason",
            field=models.CharField(blank=True, null=True, verbose_name="Block Reason"),
        ),
    ]
