# Generated by Django 5.0.6 on 2024-06-06 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum_conversation", "0010_blockedpost_block_reason"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockedpost",
            options={"verbose_name": "Blocked Post", "verbose_name_plural": "Blocked Posts"},
        ),
        migrations.AlterModelOptions(
            name="certifiedpost",
            options={
                "ordering": ["-created"],
                "verbose_name": "Certified Post",
                "verbose_name_plural": "Certified Posts",
            },
        ),
    ]
