# Generated by Django 4.2.7 on 2023-12-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metabase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=100, verbose_name="Sujet")),
                (
                    "subject_likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="Nombre de likes du sujet"),
                ),
                ("forum_name", models.CharField(max_length=100, verbose_name="Nom du forum")),
                ("poster", models.CharField(max_length=64, verbose_name="Identifiant de l'auteur")),
                ("is_anonymous_post", models.BooleanField(default=False, verbose_name="Anonyme")),
                ("certifier", models.CharField(max_length=64, null=True, verbose_name="Identifiant du certifieur")),
                ("post_upvotes_count", models.PositiveIntegerField(default=0, verbose_name="Nombre d'upvotes")),
                ("attachments_count", models.PositiveIntegerField(default=0, verbose_name="Nombre de pièces jointes")),
                ("tags_list", models.CharField(max_length=200, null=True, verbose_name="Liste des tags")),
                ("approved_boolean", models.BooleanField(default=False, verbose_name="Approuvé")),
                ("topic_created_at", models.DateTimeField(null=True, verbose_name="Date de création du sujet")),
                ("post_created_at", models.DateTimeField(null=True, verbose_name="Date de création du message")),
                (
                    "post_position_in_topic",
                    models.PositiveIntegerField(default=0, verbose_name="Position du message dans le sujet"),
                ),
                ("updates_count", models.PositiveIntegerField(default=0, verbose_name="Nombre de mises à jour")),
                ("post_last_updated_at", models.DateTimeField(null=True, verbose_name="Date de dernière mise à jour")),
                (
                    "extracted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date d'extraction des données"),
                ),
            ],
            options={
                "verbose_name": "Post Table",
                "verbose_name_plural": "Posts Table",
                "ordering": ["subject", "post_position_in_topic"],
            },
        ),
    ]
