# Generated by Django 4.2.8 on 2023-12-19 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metabase", "0003_alter_posttable_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posttable",
            name="subject_likes_count",
        ),
    ]
