# Generated by Django 4.1.5 on 2023-01-25 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("date", models.DateField(help_text="au format JJ/MM/YYYY", verbose_name="Date de début")),
                ("time", models.TimeField(help_text="au format HH:MM", verbose_name="Heure de début")),
                ("end_date", models.DateField(help_text="au format JJ/MM/YYYY", verbose_name="Date de fin")),
                ("end_time", models.TimeField(help_text="au format HH:MM", verbose_name="Heure de fin")),
                ("color", models.IntegerField(default=1, verbose_name="Color")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Notes")),
                ("location", models.URLField(blank=True, null=True, verbose_name="Lien vers l'évènement")),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Poster"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-date", "-time"],
            },
        ),
    ]
