# Generated by Django 4.1.7 on 2023-03-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailSentTrack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("status_code", models.IntegerField(verbose_name="Code de retour de l'API")),
                ("response", models.TextField(verbose_name="Réponse de l'API")),
                ("datas", models.JSONField(verbose_name="Données envoyées à l'API")),
            ],
            options={
                "verbose_name": "Trace des emails envoyés",
                "verbose_name_plural": "Traces des emails envoyés",
            },
        ),
    ]
