# Generated by Django 4.1.7 on 2023-03-20 15:15

from django.db import migrations, models

from lacommunaute.notification.enums import EmailSentTrackKind


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsenttrack",
            name="kind",
            field=models.CharField(
                choices=[
                    ("first_reply", "Première réponse à un sujet"),
                    ("onboarding", "Onboarding d'un nouvel utilisateur"),
                ],
                default=EmailSentTrackKind.FIRST_REPLY,
                max_length=15,
                verbose_name="Type",
            ),
            preserve_default=False,
        ),
    ]
