# Generated by Django 4.2 on 2023-05-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0003_alter_emailsenttrack_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="BouncedEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("reason", models.CharField(max_length=255, verbose_name="Raison")),
            ],
            options={
                "verbose_name": "Emails en erreur",
                "verbose_name_plural": "Emails en erreur",
            },
        ),
    ]
