# Generated by Django 4.2.2 on 2023-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0004_bouncedemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsenttrack",
            name="kind",
            field=models.CharField(
                choices=[
                    ("first_reply", "Première réponse à un sujet"),
                    ("following_replies", "Réponses suivantes"),
                    ("onboarding", "Onboarding d'un nouvel utilisateur"),
                    ("pending_topic", "Question sans réponse"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
