# Generated by Django 5.0.1 on 2024-02-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0005_alter_emailsenttrack_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bouncedemail",
            options={"verbose_name": "email bloqué", "verbose_name_plural": "emails bloqués"},
        ),
        migrations.AlterModelOptions(
            name="emailsenttrack",
            options={"verbose_name": "trace des emails envoyés", "verbose_name_plural": "traces des emails envoyés"},
        ),
        migrations.AlterField(
            model_name="bouncedemail",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="bouncedemail",
            name="reason",
            field=models.CharField(max_length=255, verbose_name="raison"),
        ),
        migrations.AlterField(
            model_name="emailsenttrack",
            name="datas",
            field=models.JSONField(verbose_name="données envoyées à l'API"),
        ),
        migrations.AlterField(
            model_name="emailsenttrack",
            name="kind",
            field=models.CharField(
                choices=[
                    ("first_reply", "Première réponse à un sujet"),
                    ("following_replies", "Réponses suivantes"),
                    ("onboarding", "Onboarding d'un nouvel utilisateur"),
                    ("pending_topic", "Question sans réponse"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="emailsenttrack",
            name="response",
            field=models.TextField(verbose_name="réponse de l'API"),
        ),
        migrations.AlterField(
            model_name="emailsenttrack",
            name="status_code",
            field=models.IntegerField(verbose_name="code de retour de l'API"),
        ),
    ]
