# Generated by Django 5.0.1 on 2024-02-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0006_alter_bouncedemail_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BouncedDomainName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("domain", models.CharField(max_length=253, unique=True, verbose_name="domaine")),
                ("reason", models.CharField(max_length=255, verbose_name="raison")),
            ],
            options={
                "verbose_name": "nom de domaine bloqué",
                "verbose_name_plural": "nom de domaines bloqués",
            },
        ),
    ]
