# Generated by Django 5.0.6 on 2024-06-25 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum_conversation", "0008_remove_topic_likers"),
        ("notification", "0008_delete_bounceddomainname_delete_bouncedemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("recipient", models.EmailField(max_length=254, verbose_name="recipient")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("first_reply", "Première réponse à un sujet"),
                            ("following_replies", "Réponses suivantes"),
                            ("onboarding", "Onboarding d'un nouvel utilisateur"),
                            ("pending_topic", "Question sans réponse"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "delay",
                    models.CharField(
                        choices=[("asap", "As soon as possible"), ("day", "The following day")],
                        default="asap",
                        max_length=20,
                        verbose_name="delay",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="sent at")),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="forum_conversation.post",
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
    ]
