# Generated by Django 5.0.2 on 2024-02-15 15:04

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0008_delete_bounceddomainname_delete_bouncedemail"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TagsNofication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("digest", models.BooleanField(default=False, verbose_name="digest")),
                ("newpost", models.BooleanField(default=False, verbose_name="nouveau message")),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "notification sur tag",
                "verbose_name_plural": "notifications sur tags",
            },
        ),
    ]
