# Generated by Django 5.0.2 on 2024-02-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0009_tagsnofication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsenttrack",
            name="kind",
            field=models.CharField(
                choices=[
                    ("first_reply", "Première réponse à un sujet"),
                    ("following_replies", "Réponses suivantes"),
                    ("onboarding", "Onboarding d'un nouvel utilisateur"),
                    ("pending_topic", "Question sans réponse"),
                    ("tag_digest", "Résumé de tags"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
