# Generated by Django 5.0.9 on 2024-11-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0010_alter_emailsenttrack_kind_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsenttrack",
            name="kind",
            field=models.CharField(
                choices=[
                    ("first_reply", "Première réponse à un sujet"),
                    ("following_replies", "Réponses suivantes"),
                    ("onboarding", "Onboarding d'un nouvel utilisateur"),
                    ("pending_topic", "Question sans réponse"),
                    ("magic_link", "Lien de connexion magique"),
                    ("bulk_notifs", "Notifications groupées"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("first_reply", "Première réponse à un sujet"),
                    ("following_replies", "Réponses suivantes"),
                    ("onboarding", "Onboarding d'un nouvel utilisateur"),
                    ("pending_topic", "Question sans réponse"),
                    ("magic_link", "Lien de connexion magique"),
                    ("bulk_notifs", "Notifications groupées"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
