# Generated by Django 5.0.2 on 2024-02-15 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0010_alter_emailsenttrack_kind"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TagsNofication",
            new_name="TagsNotification",
        ),
    ]
