# Generated by Django 5.1.5 on 2025-01-23 13:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0011_alter_emailsenttrack_kind_alter_notification_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="uuid",
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name="uuid"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="uuid",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="visited_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="clicked at"),
        ),
    ]
