# Generated by Django 5.1.5 on 2025-02-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0012_notification_uuid_notification_visited_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsenttrack",
            name="kind",
            field=models.CharField(
                choices=[
                    ("first_reply", "Première réponse à un sujet"),
                    ("following_replies", "Réponses suivantes"),
                    ("onboarding", "Onboarding d'un nouvel utilisateur"),
                    ("pending_topic", "Question sans réponse"),
                    ("magic_link", "Lien de connexion magique"),
                    ("bulk_notifs", "Notifications groupées"),
                    ("missyou", "Message de relance avant archivage des données"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("first_reply", "Première réponse à un sujet"),
                    ("following_replies", "Réponses suivantes"),
                    ("onboarding", "Onboarding d'un nouvel utilisateur"),
                    ("pending_topic", "Question sans réponse"),
                    ("magic_link", "Lien de connexion magique"),
                    ("bulk_notifs", "Notifications groupées"),
                    ("missyou", "Message de relance avant archivage des données"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
