# Generated by Django 5.0.9 on 2024-09-30 14:14

import django.db.models.deletion
import machina.models.fields
import storages.backends.s3
import taggit.managers
from django.db import migrations, models

import lacommunaute.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("partner", "0003_remove_partner_logo_partner_image_alter_partner_name_and_more"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                (
                    "description",
                    machina.models.fields.MarkupTextField(
                        blank=True, no_rendered_field=True, null=True, verbose_name="Description"
                    ),
                ),
                ("short_description", models.CharField(max_length=400, verbose_name="Short Description")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(bucket_name="private-bucket", file_overwrite=False),
                        upload_to="",
                        validators=[lacommunaute.utils.validators.validate_image_size],
                    ),
                ),
                ("_description_rendered", models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                (
                    "description",
                    machina.models.fields.MarkupTextField(
                        blank=True, no_rendered_field=True, null=True, verbose_name="Description"
                    ),
                ),
                ("short_description", models.CharField(max_length=400, verbose_name="Short Description")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(bucket_name="private-bucket", file_overwrite=False),
                        upload_to="",
                        validators=[lacommunaute.utils.validators.validate_image_size],
                    ),
                ),
                (
                    "certified",
                    models.BooleanField(default=False, verbose_name="Certifié par la communauté de l'inclusion"),
                ),
                ("_description_rendered", models.TextField(blank=True, editable=False, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="documentation.category",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="partner.partner"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created"],
            },
        ),
    ]
