# Generated by Django 5.0.9 on 2024-10-01 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("session_id", models.CharField(max_length=40)),
                ("rating", models.PositiveSmallIntegerField()),
                (
                    "document",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="documentation.document"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Notation d'un document",
                "verbose_name_plural": "Notations des documents",
                "ordering": ("-created",),
            },
        ),
    ]
