# Generated by Django 5.0.9 on 2024-09-19 14:09

import storages.backends.s3
from django.db import migrations, models

import lacommunaute.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(bucket_name="private-bucket", file_overwrite=False),
                upload_to="",
                validators=[lacommunaute.utils.validators.validate_image_size],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="short_description",
            field=models.CharField(default="empty", max_length=400, verbose_name="Description courte (SEO)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(bucket_name="private-bucket", file_overwrite=False),
                upload_to="",
                validators=[lacommunaute.utils.validators.validate_image_size],
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="short_description",
            field=models.CharField(default="empty", max_length=400, verbose_name="Description courte (SEO)"),
            preserve_default=False,
        ),
    ]
