# Generated by Django 4.2.8 on 2023-12-19 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DSP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("work_capacity", models.CharField(max_length=1)),
                ("language_skills", models.CharField(max_length=1)),
                ("housing", models.CharField(max_length=1)),
                ("rights_access", models.CharField(max_length=1)),
                ("mobility", models.CharField(max_length=1)),
                ("resources", models.CharField(max_length=1)),
                ("judicial", models.CharField(max_length=1)),
                ("availability", models.CharField(max_length=1)),
                ("recommendations", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User"
                    ),
                ),
            ],
            options={
                "verbose_name": "diagnostic socio-professionnel",
                "verbose_name_plural": "diagnostics socio-professionnels",
            },
        ),
    ]
