# Generated by Django 5.0.2 on 2024-02-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_recommendation_alter_dsp_availability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsp",
            name="city_code",
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name="city code"),
        ),
        migrations.AddField(
            model_name="dsp",
            name="location",
            field=models.CharField(default="---", max_length=255, verbose_name="localisation"),
            preserve_default=False,
        ),
    ]
