[[recommendations]]
codename = "capacite-travail-0"
category = "Capacité à occuper un poste de travail"
text = "Orientation vers des services médicaux pour évaluation et accompagnement"

[[recommendations]]
codename = "capacite-travail-1"
category = "Capacité à occuper un poste de travail"
text = "Mise en place d'un parcours d'insertion professionnelle personnalisé, incluant formations et immersion"

[[recommendations]]
codename = "capacite-travail-2"
category = "Capacité à occuper un poste de travail"
text = "Identifier des aménagements spécifiques nécessaires (horaires flexibles, travail à distance, etc.)."

[[recommendations]]
codename = "capacite-travail-3"
category = "Capacité à occuper un poste de travail"
text = "Détection des compétences transverses et transférables à développer"

[[recommendations]]
codename = "cours-langue-0"
category = "Langage"
text = "Identification du niveau d’illettrisme et orientation vers des formations d'alphabétisation"

[[recommendations]]
codename = "cours-langue-1"
category = "Langage"
text = "Inscription dans des programmes de Français Langue Étrangère (FLE) et de remise à niveau des savoirs de base"

[[recommendations]]
codename = "cours-langue-2"
category = "Langage"
text = "Proposer des formations en langue française adaptées à ses besoins"

[[recommendations]]
codename = "cours-langue-3"
category = "Langage"
text = "Formations complémentaires mode de communication (savoir-être…)"

[[recommendations]]
codename = "logement-0"
category = "Logement"
text = "Orientation vers des dispositifs d'urgence et des centres d'hébergement d'urgence"

[[recommendations]]
codename = "logement-1"
category = "Logement"
text = "Accompagnement social pour stabilisation et recherche de logement durable"

[[recommendations]]
codename = "logement-2"
category = "Logement"
text = "Orienter vers des services d’aide au logement et des structures d’urgence si nécessaire"

[[recommendations]]
codename = "logement-3"
category = "Logement"
text = "Surveillance de la stabilité du logement"

[[recommendations]]
codename = "access-droits-0"
category = "Accès aux droits"
text = "Information et sensibilisation sur les droits et accompagnement dans les démarches de demande"

[[recommendations]]
codename = "access-droits-1"
category = "Accès aux droits"
text = "Assistance pour la reprise des droits et accompagnement dans les démarches de renouvellement"

[[recommendations]]
codename = "access-droits-2"
category = "Accès aux droits"
text = """
       Soutien dans les démarches administratives, \
       notamment pour stabiliser la situation de logement et de garde des enfants\
       """

[[recommendations]]
codename = "access-droits-3"
category = "Accès aux droits"
text = "Vérifier la continuité des droits et assurer un suivi administratif"

[[recommendations]]
codename = "mobilite-0"
category = "Mobilité"
text = "Mise en place d'un accompagnement pour apprendre à utiliser les transports en commun ou d’une formation à la conduite"

[[recommendations]]
codename = "mobilite-1"
category = "Mobilité"
text = "Aide pour la mise en règle des documents du véhicule et sensibilisation à l'importance de l'assurance et du contrôle technique"

[[recommendations]]
codename = "mobilite-2"
category = "Mobilité"
text = """
       Évaluer les besoins de mobilité spécifiques liés à la garde des enfants et  \
       au travail possibilité de mise en place de mobilité solidaire\
       """

[[recommendations]]
codename = "mobilite-3"
category = "Mobilité"
text = "Encourager l’usage du covoiturage, valoriser la mobilité dans la recherche d’emploi"

[[recommendations]]
codename = "ressources-0"
category = "Situation financière"
text = "Evaluer et lister le niveau d’endettement"

[[recommendations]]
codename = "ressources-1"
category = "Situation financière"
text = "Suivi du dossier de surendettement et accompagnement vers une gestion budgétaire saine"

[[recommendations]]
codename = "ressources-2"
category = "Situation financière"
text = """
       Accompagnement en gestion budgétaire, orientation vers des aides financières et \
       des conseils en économie sociale et familiale\
       """

[[recommendations]]
codename = "ressources-3"
category = "Situation financière"
text = "Ateliers de gestion budgétaire avancée si nécessaire"

[[recommendations]]
codename = "judiciaire-0"
category = "Situation judiciaire"
text = """
       Initiatives permettant aux personnes sortant de prison de disposer \
       d’un projet de réinsertion, avec un accompagnement global adapté (Fondation de France)\
       """

[[recommendations]]
codename = "judiciaire-1"
category = "Situation judiciaire"
text = """
       Coordination avec les services judiciaires pour un accompagnement adapté et \
       respectueux des obligations judiciaires\
       """

[[recommendations]]
codename = "judiciaire-2"
category = "Situation judiciaire"
text = "Sensibilisation aux conséquences de comportements à risque"

[[recommendations]]
codename = "disponibilite-0"
category = "Disponibilité"
text = "Proposition de solutions de garde d'enfants ou d'aide à la personne pour permettre une meilleure disponibilité"

[[recommendations]]
codename = "disponibilite-1"
category = "Disponibilité"
text = "Orientation vers des services de soutien familial pour aider à l'organisation du quotidien"

[[recommendations]]
codename = "disponibilite-2"
category = "Disponibilité"
text = "Recherche d'emplois compatibles avec les horaires de garde des enfants, exploration d'opportunités de travail à temps partiel ou flexible"

[[recommendations]]
codename = "disponibilite-3"
category = "Disponibilité"
text = "Prêt à l’emploi, proposition d’atelier TRE"

[[recommendations]]
codename = "toutes-les-formations"
category = "Général"
text = "Se diriger vers le conseil départemental pour définir les priorités d’accompagnement"

[[recommendations]]
codename = "pret-a-emploi"
category = "Général"
text = "Démarrer un parcours dans l’IAE sur les emplois de l’inclusion"
