# Generated by Django 5.0.6 on 2024-06-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0015_alter_forumrating_options"),
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "period",
                    models.CharField(
                        choices=[("month", "Month"), ("week", "Week"), ("day", "Day")],
                        max_length=10,
                        verbose_name="Période",
                    ),
                ),
                ("visits", models.IntegerField(default=0, verbose_name="Visites")),
                ("entry_visits", models.IntegerField(default=0, verbose_name="Visites entrantes")),
                ("time_spent", models.IntegerField(default=0, verbose_name="Temps passé")),
                (
                    "forum",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="forum.forum", verbose_name="Forum"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stat de forum",
                "verbose_name_plural": "Stats de forum",
                "ordering": ["date", "period", "forum"],
                "unique_together": {("date", "period", "forum")},
            },
        ),
    ]
