# Generated by Django 5.0.9 on 2024-09-19 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("stats", "0002_forumstat"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentationStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField()),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "period",
                    models.CharField(
                        choices=[("month", "Month"), ("week", "Week"), ("day", "Day")],
                        max_length=10,
                        verbose_name="Période",
                    ),
                ),
                ("visits", models.IntegerField(default=0, verbose_name="Visites")),
                ("entry_visits", models.IntegerField(default=0, verbose_name="Visites entrantes")),
                ("time_spent", models.IntegerField(default=0, verbose_name="Temps passé")),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "Stat de la documentation",
                "verbose_name_plural": "Stats de la documentation",
                "ordering": ["date", "period", "content_type", "object_id"],
                "unique_together": {("date", "period", "content_type", "object_id")},
            },
        ),
    ]
