# Generated by Django 4.2.9 on 2024-01-24 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0012_forum_short_description_alter_forum_kind"),
        ("forum_conversation", "0008_remove_topic_likers"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicReadTrack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mark_time", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="forum_conversation.topic",
                        verbose_name="Topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_tracks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic track",
                "verbose_name_plural": "Topic tracks",
                "abstract": False,
                "unique_together": {("user", "topic")},
            },
        ),
        migrations.CreateModel(
            name="ForumReadTrack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mark_time", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="forum.forum",
                        verbose_name="Forum",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_tracks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum track",
                "verbose_name_plural": "Forum tracks",
                "abstract": False,
                "unique_together": {("user", "forum")},
            },
        ),
    ]
