# Generated by Django 4.2.9 on 2024-01-24 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0012_forum_short_description_alter_forum_kind"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "codename",
                    models.CharField(db_index=True, max_length=150, unique=True, verbose_name="Permission codename"),
                ),
            ],
            options={
                "verbose_name": "Forum permission",
                "verbose_name_plural": "Forum permissions",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserForumPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("has_perm", models.BooleanField(db_index=True, default=True, verbose_name="Has perm")),
                (
                    "anonymous_user",
                    models.BooleanField(db_index=True, default=False, verbose_name="Target anonymous user"),
                ),
                (
                    "authenticated_user",
                    models.BooleanField(db_index=True, default=False, verbose_name="Target any logged in user"),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum.forum",
                        verbose_name="Forum",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum_permission.forumpermission",
                        verbose_name="Forum permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User forum permission",
                "verbose_name_plural": "User forum permissions",
                "abstract": False,
                "unique_together": {("permission", "forum", "user")},
            },
        ),
        migrations.CreateModel(
            name="GroupForumPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("has_perm", models.BooleanField(db_index=True, default=True, verbose_name="Has perm")),
                (
                    "forum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum.forum",
                        verbose_name="Forum",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group", verbose_name="Group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum_permission.forumpermission",
                        verbose_name="Forum permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group forum permission",
                "verbose_name_plural": "Group forum permissions",
                "abstract": False,
                "unique_together": {("permission", "forum", "group")},
            },
        ),
    ]
