import datetime

from django.conf import settings


INCLUSION_CONNECT_SCOPES = "openid profile email"

INCLUSION_CONNECT_CLIENT_ID = settings.INCLUSION_CONNECT_CLIENT_ID
INCLUSION_CONNECT_CLIENT_SECRET = settings.INCLUSION_CONNECT_CLIENT_SECRET

INCLUSION_CONNECT_ENDPOINT = "{base_url}/auth".format(
    base_url=settings.INCLUSION_CONNECT_BASE_URL,
)
INCLUSION_CONNECT_ENDPOINT_AUTHORIZE = f"{INCLUSION_CONNECT_ENDPOINT}/authorize/"
INCLUSION_CONNECT_ENDPOINT_REGISTRATIONS = f"{INCLUSION_CONNECT_ENDPOINT}/register/"
INCLUSION_CONNECT_ENDPOINT_TOKEN = f"{INCLUSION_CONNECT_ENDPOINT}/token/"
INCLUSION_CONNECT_ENDPOINT_USERINFO = f"{INCLUSION_CONNECT_ENDPOINT}/userinfo/"
INCLUSION_CONNECT_ENDPOINT_LOGOUT = f"{INCLUSION_CONNECT_ENDPOINT}/logout/"

# These expiration times have been chosen arbitrarily.
INCLUSION_CONNECT_TIMEOUT = 60

INCLUSION_CONNECT_SESSION_KEY = "inclusion_connect"

# This expiration time has been chosen arbitrarily.
OIDC_STATE_EXPIRATION = datetime.timedelta(hours=1)
