# Generated by Django 5.0.6 on 2024-06-27 15:09

import django.db.models.deletion
import machina.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Edito",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "content",
                    machina.models.fields.MarkupTextField(
                        blank=True, no_rendered_field=True, null=True, verbose_name="Contenu"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL du lien")),
                ("link_title", models.CharField(max_length=100, verbose_name="Titre du lien")),
                ("_content_rendered", models.TextField(blank=True, editable=False, null=True)),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Poster"
                    ),
                ),
            ],
            options={
                "verbose_name": "Edito",
                "verbose_name_plural": "Editos",
                "ordering": ["-updated"],
            },
        ),
    ]
