# Generated by Django 4.1.2 on 2022-10-18 09:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forum_conversation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicPoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "question",
                    models.CharField(max_length=255, verbose_name="Poll question"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Poll duration, in days"),
                ),
                (
                    "max_options",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Maximum number of poll options per user",
                    ),
                ),
                (
                    "user_changes",
                    models.BooleanField(default=False, verbose_name="Allow vote changes"),
                ),
                (
                    "topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll",
                        to="forum_conversation.topic",
                        verbose_name="Topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic poll",
                "verbose_name_plural": "Topic polls",
                "ordering": ["-updated"],
                "get_latest_by": "updated",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TopicPollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Poll option text"),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="forum_polls.topicpoll",
                        verbose_name="Poll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic poll option",
                "verbose_name_plural": "Topic poll options",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TopicPollVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymous_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Anonymous user forum key",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vote's date"),
                ),
                (
                    "poll_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="forum_polls.topicpolloption",
                        verbose_name="Poll option",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Voter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic poll vote",
                "verbose_name_plural": "Topic poll votes",
                "abstract": False,
            },
        ),
    ]
