# Generated by Django 4.2.9 on 2024-01-24 14:31

import django.db.models.deletion
import machina.apps.forum_member.abstract_models
import machina.core.validators
import machina.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "avatar",
                    machina.models.fields.ExtendedImageField(
                        blank=True,
                        null=True,
                        upload_to=machina.apps.forum_member.abstract_models.get_profile_avatar_upload_to,
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "signature",
                    machina.models.fields.MarkupTextField(
                        blank=True,
                        no_rendered_field=True,
                        null=True,
                        validators=[machina.core.validators.MarkupMaxLengthValidator(255)],
                        verbose_name="Signature",
                    ),
                ),
                ("posts_count", models.PositiveIntegerField(blank=True, default=0, verbose_name="Total posts")),
                ("_signature_rendered", models.TextField(blank=True, editable=False, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum profile",
                "verbose_name_plural": "Forum profiles",
                "abstract": False,
            },
        ),
    ]
