# Generated by Django 5.0.2 on 2024-02-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum_member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumprofile",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cv/", verbose_name="votre CV"),
        ),
        migrations.AddField(
            model_name="forumprofile",
            name="internship_duration",
            field=models.IntegerField(default=0, verbose_name="durée du stage (en mois)"),
        ),
        migrations.AddField(
            model_name="forumprofile",
            name="linkedin",
            field=models.URLField(blank=True, null=True, verbose_name="lien vers votre profil LinkedIn"),
        ),
        migrations.AddField(
            model_name="forumprofile",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XX", "---------"),
                    ("00", "France entière"),
                    ("84", "Auvergne-Rhône-Alpes"),
                    ("27", "Bourgogne-Franche-Comté"),
                    ("53", "Bretagne"),
                    ("24", "Centre-Val de Loire"),
                    ("94", "Corse"),
                    ("44", "Grand Est"),
                    ("01", "Guadeloupe"),
                    ("03", "Guyane"),
                    ("32", "Hauts-de-France"),
                    ("11", "Île-de-France"),
                    ("04", "La Réunion"),
                    ("02", "Martinique"),
                    ("06", "Mayotte"),
                    ("28", "Normandie"),
                    ("75", "Nouvelle-Aquitaine"),
                    ("76", "Occitanie"),
                    ("52", "Pays de la Loire"),
                    ("93", "Provence-Alpes-Côte d’Azur"),
                ],
                default="XX",
                max_length=100,
                null=True,
                verbose_name="région",
            ),
        ),
        migrations.AddField(
            model_name="forumprofile",
            name="search",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO", "Je ne suis pas en recherche"),
                    ("INTERNSHIP", "Je suis en recherche active de stage de CIP"),
                    ("APPRENTICESHIP", "Je suis en recherche active d'apprentissage de CIP"),
                ],
                default="NO",
                max_length=20,
                null=True,
                verbose_name="recherche active",
            ),
        ),
        migrations.AddField(
            model_name="forumprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
